SRCFILES =  utilities/SimpleWeightedSelector.cpp \
            utilities/ParameterizedWeightedSelector.cpp \
            utilities/Utilities.cpp \
            utilities/FileWriter.cpp \
            socialnetwork_toolkit/Scenario.cpp \
            socialnetwork_toolkit/Payload.cpp \
            socialnetwork_toolkit/InfoStore.cpp \
            socialnetwork_toolkit/InfoID.cpp  \
            platforms/GitHub/GitHub_Feed.cpp \
            platforms/GitHub/GitHub_Payload.cpp \
            platforms/GitHub/GitHub_Network.cpp \
            platforms/GitHub/GitHub_Action.cpp \
			platforms/GitHub/GitHub_User_Agent.cpp \
            platforms/GitHub/GitHub_Feed_Query.cpp \
            platforms/Jamii/Jamii_Feed_Query.cpp \
            platforms/Jamii/Jamii_Feed.cpp \
            platforms/Jamii/Jamii_Payload.cpp \
            platforms/Jamii/Jamii_User_Agent.cpp \
            platforms/Jamii/Jamii_Action.cpp \
            platforms/Jamii/Jamii_Network.cpp \
			platforms/Reddit/Reddit_Feed.cpp \
            platforms/Reddit/Reddit_Payload.cpp \
			platforms/Reddit/Reddit_Network.cpp \
            platforms/Reddit/Reddit_Action.cpp \
			platforms/Reddit/Reddit_Agent_Post.cpp \
			platforms/Reddit/Reddit_User_Agent.cpp \
			platforms/Reddit/Reddit_Feed_Query.cpp \
			platforms/Telegram/Telegram_Feed.cpp \
            platforms/Telegram/Telegram_Payload.cpp \
			platforms/Telegram/Telegram_Network.cpp \
            platforms/Telegram/Telegram_Action.cpp \
			platforms/Telegram/Telegram_Agent_Conversation.cpp \
			platforms/Telegram/Telegram_User_Agent.cpp \
			platforms/Telegram/Telegram_Agent.cpp \
			platforms/Telegram/Telegram_Feed_Query.cpp \
			platforms/Twitter/Twitter_Feed.cpp \
            platforms/Twitter/Twitter_Payload.cpp \
			platforms/Twitter/Twitter_Network.cpp \
			platforms/Twitter/Twitter_Action.cpp \
			platforms/Twitter/Twitter_Agent_Conversation.cpp  \
			platforms/Twitter/Twitter_User_Agent.cpp \
			platforms/Twitter/Twitter_Feed_Query.cpp \
			platforms/YouTube/YouTube_Feed.cpp \
            platforms/YouTube/YouTube_Payload.cpp  \
			platforms/YouTube/YouTube_Network.cpp  \
			platforms/YouTube/YouTube_Action.cpp   \
			platforms/YouTube/YouTube_Agent_Video.cpp  \
			platforms/YouTube/YouTube_User_Agent.cpp \
			platforms/YouTube/YouTube_Agent.cpp \
			platforms/YouTube/YouTube_Feed_Query.cpp
